# slurm 数据库配置
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  dbname: slurm_acct_db
  password: 81SLURM@@rabGTjN7
  clustername: cluster

ldap:
  ip: 127.0.0.1
  port: 389
  basedn: ou=People,ou=hpc,o=pku
  binddn: cn=Manager,ou=hpc,o=pku
  password: admin

loginNode:
  - login01